### PR TITLE
Boilermaker updates

### PR DESCRIPTION
**Pull request by b17z-fsa**
### Assignee Tasks
* Updated a bunch of the packages 

### Guidelines
It has been a while since the boilermaker repo has been updated so there were a few security vulnerabilities generated from lack of updates. I did avoid updating react-redux until I tested a few things in projects because it has been known to have some issues with versioning against other react- modules.

---

From Slack Academics Slack Channel: "I went through each package its dependency tree almost all manually to avoid updating things that don't need to be updated. So, I followed a format like given X.Y.Z, if X (major) was not on the correct number, it was updated, and if Y (minor) was like something larger, it was updated. Z (patches) wasn't really touched."

### CODE REVIEW

**Comment by collin** [comment]
At face value this seems like a good thing.

Might be worth sending this to a few fellows to try and run against their grace shopper projects to see if anything breaks in an obvious way.

**Comment by glebec** [comment]
Related to #165

**Comment by leafoflegend** [comment]
@b17z-fsa I tested this out locally last night in some free time and the commands all seemed to work as expected. It would be nice if you are introducing a change log to maybe automate some aspect of the change log or change CI to expect it? Thats really my only comment.

I didn't heavily test it however and agree with https://github.com/FullstackAcademy/boilermaker/pull/168#issuecomment-481455666 that having fellows give this a more thorough test could be worthwhile.

**Comment by b17z-fsa** [comment]
@leafoflegend Yeah, I can do that. I should have done that and will do that a bit later.
@collin Thanks for confirming/testing. I was having a few of the fellows look at it.

**Pull request merged**
