### PR TITLE
Use .jsx file extension instead of .js

### PR DESCRIPTION
**Pull request by briandk**
## The Problem

On my machine, prettier barfs on `.js` files that contain JSX syntax.

## My Solution

Rename JSX-containing files to have a `.jsx` extension, which prettier will recognize. 

## Is this really necessary?

Yeah, I know, there are debates about this. I fall on the side of airbnb here: https://github.com/airbnb/javascript/issues/1235#issuecomment-428413675

## But Brian, what if it's just that your prettier is configured incorrectly?

That could be. Any help would be appreciated

## Is there any argument for this change outside of appeasing prettier?

When navigating a project at a high-level, you can more easily see any modules that are using JSX syntax. It's arguably the same reason we use types when we can: the extra info reflects intent.

### CODE REVIEW

**Comment by collin** [comment]
I think there are still some projects/examples around that might use `.jsx` file names. We're also guilty of using capitalized letters in filenames, which can create some terribly confusing naming issues.

This would be a good topic for a PEP style document covering naming conventions.

**Comment by glebec** [comment]
On a separate note, while I don't (yet) see any evidence that we should choose `.jsx` over `.js` for the purpose of compatibility with Prettier, I will point out that one small advantage of `.jsx` is that VSC supports Emmet-expansion in JSX files by default.

**Comment by glebec** [comment]
So, having worked on this for a couple hours now with @briandk, we've determined that the issue is something to do with VSC extensions and not Boilermaker per se. It seems to be a regression bug because after disabling all VSC extensions and then bringing them all back online, my VSC now exhibits the same behavior and I cannot recover the working integration of `format on save`. However, the project scripts themselves (e.g. `npm run prettify`, git hook prettify, CLI use of prettier etc.) work fine. So this is something to do with VSC specifically.

**Comment by collin** [comment]
Oh bother.

On the other hand, congratulations on putting this together in such a rock-solid way it took an EDITOR INTEGRATION BUG to bring things down. 🔥

**Comment by briandk** [comment]
@collin @glebec The saga continues: https://github.com/prettier/prettier-vscode/pull/708

**Comment by glebec** [comment]
Question: do we want to make this change anyway for other reasons, e.g. for emmet support? Or should we close this PR?

**Comment by glebec** [comment]
Closing and re-opening to trigger Travis build (Travis was toggled on after this PR was opened).

**Comment by jbracht** [comment]
I'd be down to move to `.jsx` instead of `.js` solely for emmet support (and I guess also the added benefit of being able to quickly browse js/jsx files and easily tell which ones are React components and which files are "other stuff")

HOWEVER - there's the inconvenience issue I have with this being: you can no longer do `import Component from './Component'` unless it ends in `.js`. If it's `.jsx`, you must include that extension on your import. There's gotta be some config somewhere where you can specify "hey check for `.js` AND `.jsx` on imports" and then I'd be hella game.

**Comment by glebec** [comment]
@jbracht — there is a Webpack config option for that, “resolvers” or something similar.

**Comment by shiraze** [comment]
> On a separate note, while I don't (yet) see any evidence that we should choose `.jsx` over `.js` for the purpose of compatibility with Prettier, I will point out that one small advantage of `.jsx` is that VSC supports Emmet-expansion in JSX files by default.

I'd also say that using something like the Material theme in VS Code (https://marketplace.visualstudio.com/items?itemName=Equinusocio.vsc-material-theme)  could be used to highlight files that exclusively contain 'code' and those whose primary purpose is to render a react componet

**Pull request closed without merging**
